routes:
  - path: "/getos"
    script: "/getos.sh"
  - path: "/ajenti"
    30x: "https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh"
  - path: "/certbot_deb.sh"
    script: "/certbot_deb.sh"
  
  #proxmox
  - path: "/proxmox-5"
    script: "/proxmox-5.sh"
  - path: "/proxmox-6"
    script: "/proxmox-6.sh"
  - path: "/proxmox"
    30x: "https://{{domain}}/getos?deb_10X=/proxmox-6.sh&deb_9X=/proxmox-5.sh" 
  
  - path: "/ogp-agent.deb"
    script: "/ogp-agent_deb.sh"
  - path: "/ogp-agent.rpm"
    script: "/ogp-agent_rpm.sh"

  - path: "/runtime/nvm"
    30x: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh"
  - path: "/runtime/nvm-((\\d+).(\\d+).(\\d+))"
    30x: "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ pram_2 }}/install.sh"

  - path: "/panel/webmin.deb"
    script: "/panel/webmin_deb.sh"
  - path: "/panel/webmin.rpm"
    script: "/panel/webmin_rpm.sh"    
  - path: "/panel/vestacp"
    30x: "http://vestacp.com/pub/vst-install.sh"
  - path: "/panel/cpanel"
    30x: "https://securedownloads.cpanel.net/latest"
  - path: "/panel/cpanel-dns"
    30x: "https://securedownloads.cpanel.net/latest-dnsonly"

  - path: "/mac/homebrew"
    30x: "https://raw.githubusercontent.com/Homebrew/install/master/install"

  - path: "/pterodactyl/daemon"
    script: "/pterodactyl/daemon.sh"

  - path: "/centos/webpanel"
    script: "/centos/webpanel.sh"

  - path: "/net/plesk"
    30x: "https://autoinstall.plesk.com/one-click-installer"
  - path: "/net/mail-cow"
    script: "/net/mail-cow.sh"

  - path: "/mc/amp"
    30x: "https://cubecoders.com/getamp.sh"
  - path: "/pufferpanel"
    script: "/mc/pufferpanel.sh"




